- OntologyFiles/bundle-catalog-v001.xml
- OntologyFiles/catalog-v001.xml
- bundle.bat
I noticed the catalog-v001.xml file in develop was broken in terms of being useful for when I am editing as a developer, from a git checkout.  It mapped to filenames with X.x.x in them, but our development files do not have that.  
It turns out we need 2 catalog files under source control. 
One, catalog-v001.xml, that works for developers editing from a git checkout
(that maps to non-numbered file names)
Another, bundle-catalog-v001.xml that is a template for
the catalog file provided in the web download (used by the "bundle.bat" script)
I updated the bundle.bat script and confirmed that both catalog files work for their respective purposes.
> Fix catalog files

- OntologyFiles/gistWiki.owl
Found this while gathering ontology metrics.
> Correct namespace to https for gistWiki

- OntologyFiles/gistAddress.owl
- OntologyFiles/gistAgreement.owl
- OntologyFiles/gistCategory.owl
- OntologyFiles/gistContent.owl
- OntologyFiles/gistCore.owl
- OntologyFiles/gistDeprecated.owl
- OntologyFiles/gistEvent.owl
- OntologyFiles/gistIntention.owl
- OntologyFiles/gistIoT.owl
- OntologyFiles/gistMagnitude.owl
- OntologyFiles/gistMeasure.owl
- OntologyFiles/gistNetwork.owl
- OntologyFiles/gistOrganization.owl
- OntologyFiles/gistPlace.owl
- OntologyFiles/gistTemporalRelation.owl
- OntologyFiles/gistTime.owl
- OntologyFiles/gistTop.owl
- OntologyFiles/gistUnit.owl
- OntologyFiles/gistUnitDim.owl
@sa-bpelakh I believe ontology-toolkit adds the correct versionInfo, so they don't need to be in the source files. Can you confirm that?
> Remove e6Tools version info

- bundle.yaml
The bundle changes have merged into https://github.com/semanticarts/ontology-toolkit, so here is the gist bundle I tested it with - just wanted it ready for the April milestone.
> Bundle template

- doc/ChangeAndReleaseManagement.md
Note: A previous PR #235 moved the directory doc to docs. If that PR has already been merged, the change to docs should be accepted.
Please proposed corrections if I've gotten something wrong, since I haven't been through the release process myself.
> First version of ChangeAndReleaseManagement documentation

- bundle.yaml
Can be used once https://github.com/semanticarts/ontology-toolkit/pull/22 is approved.
> Rename ontology files by appending version.

- OntologyFiles/gistMeasure.owl
In the current model of each Ordered Member being
in at most 1 ordered list, the orderedMemberOf
property should be functional. Fixes #262
> orderedMemberOf is Functional, not Inverse Functional

- gistCore.owl
This is a re-do, without a problem with serialization.
"A way to categorized a behavior" was changed to "A way to categorize a behavior."
Signed-off-by: Meika Ungricht <meika.ungricht@semanticarts.com>
> Issue 168 - grammar fix.

- gistCore.owl
Fixes #104, #107 
Although adding transitivity to hasSuperCategory and hasSubCategory can affect inferencing, we regard this as error correction and thus is considered a patch rather than a major change.
Adding two new properties is a minor change, as it represents new functionality.
> Category relationships

- docs/ReleaseNotes.md
Document changes since 9.3.0. We should make sure that every PR that introduces significant (non-admin) changes includes a change to this section.
@rjyounes @daliadahleh Please verify that I accurately summarized your PRs.
> Add 'Next Release' section

- gistCore.ttl
> Remove redundant subclass assertion in definition of GeoRoute

- bundle.yaml
This will only `legacyAnnotations.ttl` via CONSTRUCT query to restore the old `rdfs:label`/`rdfs:comment` annotations. I don't know the right release notes verbiage or whether we should also have a JSON-LD and RDF/XML versions of this file. 
PS This requires onto_tool v0.10.0 or later (including the fix in https://github.com/semanticarts/ontology-toolkit/pull/47, which is not yet merged at this time).
> Generate legacy annotations. Fixes #379

- bundle.yaml
- docs/ReleaseNotes.md
- gistCore.ttl
- gistValidationAnnotations.ttl
- ontologyShapes.ttl
Created rules for Title Case, Lower Case and Sentence Case, and associated with classes and properties. Also mandated at least one `skos:definition` for each ontology entity. You can run `onto_tool` to see how the validation outputs, and we can convert these to warnings for the time being so they don't abort the build, until we can actually change the labels. 
I think the regex work with the current labels, but we may need to augment to support numbers, dashes, etc, which are currently all excluded.
> Label validation

- docs/ReleaseNotes.md
- gistCore.ttl
Add datatype property ```gist:description```.
> Add property gist:description. Fixes #425.

- bundle.yaml
- docs/ReleaseNotes.md
- gistCore.ttl
Just cosmetics and a small fix for new labels introduced by Michael which were not compliant. Had to indent the nested lists in the release notes 4 spaces instead of 2 so they would be properly formatted by the markdown2HTML conversion.
> v9.6.0: Correct labels to be compliant, formatting for release notes.

- bundle.yaml
Specifically enumerated included files so that random RDF does not get included in the release. Reordered serialization action to streamline transform.
@dhurlburtusa Can you please run a sample build and make sure only the expected contents make it into the generated distribution?
> Don't include extraneous content in release build. Fixes #438

- docs/.markdownlint.json
- docs/ChangeAndReleaseManagement.md
- docs/ReleaseNotes.md
- gistCore.ttl
- gistDeprecated.ttl
Since this is for major release 10.0.0, the class is removed rather than deprecated.
> Remove gist:Room. Fixes #102

- docs/.markdownlint.json
- docs/ReleaseNotes.md
- gistCore.ttl
@uschold:  Please review scope notes on `gist:hasBirthDate`. It may be extraneous detail, but I'm trying to clarify the meaning relative to different types of living things, given that there had been a mention of plants. Perhaps a better option is to remove all mention of other organisms, simply define it as the date something is born, and leave it up to the scientists to specify exactly what that means. Let me know what you think.
Boris has approved this but please comment.
> Changes to gist:Person and gist:hasBirthDate. Fixes #136.

- docs/ReleaseNotes.md
- gistCore.ttl
The changes in PR 449 were major changes. The next major release has been postponed by one month, so the changes need to be reverted for 9.7.0 and restored for 10.0.0.
> Revert changes to gist:Person and gist:hasBirthDate. Fixes #458.

- docs/ReleaseNotes.md
I had to make a small fix in ReleaseNotes for proper HTML rendering. This is due to a bug in the python Markdown module that messes up nested lists. As soon as you inspect, I can proceed w/ the release process, I have already regenerated the archive as part of testing this patch.
> Fix nested list indents in ReleaseNotes.

- docs/ReleaseNotes.md
- gistCore.ttl
> Domain range includes

- bundle.yaml
- docs/ReleaseNotes.md
- gistCore.ttl
- gistMediaTypes.ttl
- ontologyShapes.ttl
@mkumba There was extensive debate about this issue, and your input was requested. I followed the approach @Jamie-SA and I favored, which was to create annotations for existing IANA media type pages by adding types and labels.
@rjyounes and some others said we should not be creating statements using entities we do not own as subjects, and suggested I follow this pattern instead:
```
gist:_MediaType_TextHtml 
a gist:MediaType; 
gist:uniqueText "text/html";
owl:sameAs iana:text\/html .
```
Creating a duplicate instance in the `gist` namespace for each of the media types. Do you have strong feeling in either direction?
> Rename MimeType to MediaType, create ontology to declare instances. Fixes #434, #463

- tools/pre-commit
Update rdf-toolkit to address the [serialization issue](https://github.com/edmcouncil/rdf-toolkit/issues/15), update pre-commit hook to match new invocation syntax.
> Upgrade rdf-toolkit and update pre-commit hook to match.

- docs/ReleaseNotes.md
- gistCore.ttl
- Renamed `decimalValue` to `numericValue`
- Changes to `Person`, including `name` and `hasBirthDate`
- Refactored network connections, renaming properties and tightening up their definition
- Clarified definition of `ContemporaneousEvent`
Tagging @Jamie-SA for `numericValue`, the usual suspects for the rest.
> Addressing multiple issues for v10.0.0. Fixes #126, #136, #171, #174.

- bundle.yaml
- docs/ReleaseNotes.md
- gistCore.ttl
- validation_queries/property_type_construct.rq
I also added validation that super/inverse properties have to be the same type as the source property (i.e. ObjectProperty can't have a DatatypeProperty as a super-property). I did _not_, however, mandate that the parent or inverse are defined, in case we are referencing a property defined elsewhere. Let me know if this is something we want to enforce - it would prevent referencing an unresolved URI due to a typo. Might want to also add referential integrity checks for classes at some point (e.g. `subClassOf` or `disjointWith`).
> Refactor physical addresses, Fixes #483

- bundle.yaml
The issue introduced by the Java11-based `rdf-toolkit` is the inability to serialize in place - the input and output files have to be different. For some reason I did not catch this when testing, and we have no automated sanity test in place to make sure the formatted output is similar to the input - that's a deficiency to consider.
Regardless, I modified the build to rename the Turtle files during formatting, then move them back. No need to do for any of the others, since they have different extensions, so they are not overwritten.
> Rename on format then rename back to avoid serialization issue.

- gistCore.ttl
This change clarifies the meaning of the restriction, though it is strictly speaking logically redundant: since only `OrderedMember`s belong to `OrderedCollection`s, precedence would be only in relation to other `OrderedMember`s. There's an edge case counterexample where an `OrderedMember` is asserted to precede or follow something outside the `OrderedCollection`, but it's hard to see how that situation would occur. At any rate, this creates greater clarity.
> Clarify restrictions on OrderedMember

- docs/ReleaseNotes.md
- gistCore.ttl
- gistDeprecated.ttl
- migration/v10.0/detect_removed.rq
This property should have been removed as per issue 540. While the other changes proposed in that issue were implemented, the property itself was not removed.
> Deprecated gist:hasOrderedMember

- gistCore.ttl
```markdown
Release notes gist x.x.x
-----
- Removed domain and range for `gist:hasNumerator`, `gist:hasDenominator`, `gist:hasMultiplier`, and `gist:hasMultiplicand`. Issue [#160](https://github.com/semanticarts/gist/issues/160). 
```
> Generalize the properties :numerator, :denominator, :multiplier, and :multiplicand. Fixes #160. 

- tools/pre-commit
Minimum version number is now 11, not 7.
> Update minimum Java version needed to run rdf-toolkit

- docs/ReleaseNotes.md
- gistCore.ttl
Corrected the local name and made a quick fix to the definition so that it's intelligible. Further work on the definition is called for in #148.
The history of this is that when local names were updated in gist 10, the meaning of the predicate was misunderstood and so changed. I realized the mistake and have now changed it back.
> Rename hasJurisdictionOver. Fixes #637.

- docs/ReleaseNotes.md
- gistCore.ttl
Eliminated :standardConversionFactor and :baseConversionFactor. Created :conversionFactor instead with cleaned up annotations.
Added cardinality restrictions of 1 to :UnitOfMeasure for :conversionFactor and :hasStandardUnit
Removed cardinality restriction on :hasBaseUnit in :SimpleUnitOfMeasure
> Combine standard and base conversion factor predicates into a single `conversionFactor` predicate. Fixes #624.

- docs/ReleaseNotes.md
- gistCore.ttl
Datetimes with 00 for months or days violates the xsd format. Corrected example and notes.
> Correct notes on year-precision predicates. Fixes #652.

- gistCore.ttl
Fixes #661
Update scopenote on gist:name to use the correct property name that was previously updated.
> Fixes #661: update scopenote with isIdentifiedBy

- docs/ReleaseNotes.md
- gistCore.ttl
Note that the release notes in this PR include the release note from PR 674, because the updated annotations are included in a single release note.
> Update annotations on gist:uniqueText. Fixes #577.

- docs/ReleaseNotes.md
- gistCore.ttl
- ontologyShapes.ttl
While adding the triple to indicate that `isConnectedTo` is symmetric, I received a SHACL validation error that `owl:SymmetricProperty` is an undefined class. To address this, I have added `owl:SymmetricProperty` to the list of classes in InstanceShape within ontologyShapes.ttl.
> Make `gist:isConnectedTo` symmetric. Fixes #699.

- docs/ReleaseNotes.md
- gistCore.ttl
> BugFix: isRecordedAt is now a subproperty of gist:atDateTime. Fixes #726.

- docs/ReleaseNotes.md
- gistCore.ttl
- gistDeprecated.ttl
Issue [#692](https://github.com/semanticarts/gist/issues/692).
Removed and deprecated `gist:_greenwichTimeZone`, `gist:_one_day`, `gist:_one_millisecond`, and `gist:_one_minute`.
> Removed and deprecated obsolete instances. Fixes #692.

- docs/ReleaseNotes.md
- gistCore.ttl
- ontologyShapes.ttl
This PR includes:
1. Changed the definition of `gist:precedes` to exclude same order. 
2. Added OWL type assertions to `gist:precedes`, `gist:precedesDirectly`, and `gist:followsDirectly` to formally express this (asymmetric and irreflexive).
3. Updated ontologyShapes.ttl to accept these OWL types.
4. Added scope notes to `gist:precedesDirectly` and `gist:followsDirectly` about how to express same order.
5. Added predicate `gist:follows`, since during this work it was found to be missing.
6. A few miscellaneous modifications to gistDeprecated.ttl and the release notes.
Item 5 is technically beyond the scope of issue #300, but given that it's a bug fix it seemed acceptable to add it here.  Item 6 is also outside the scope but address small omissions I noted along the way.
> Changes to precedes and follows predicates. Fixes #300.

- docs/Contributing.md
- docs/release_notes/pr795.md
- tools/pre-commit
- tools/serializer/pre-commit
- tools/setup.sh
Fixes #794
- Fix serialize pre-commit hook
- Make sure the script starts in the root directory of the repository
- Correct the path to serializer
- Add file to the commit after the sed command
- Preserve file permissions during processing steps
- Return a failure code (non zero return value) when the serializer fails
- Add new "root" pre-commit hook
- Prevent commits to these branches: develop, main, master
- Then run the serializer pre-commit hook
- Add a setup.sh file to install the pre-commit hook
- Update the documentation a little
Everyone should run the script `./tools/setup.sh` after pulling in these changes.
> Changes to pre commit hook. Fixes #794

- bundle.yaml
Fixes #754.
No release note - too trivial to document.
Only one change was made, to the message value on the RDFS annotation action. Other changes were too trivial to bother with, and I don't actually understand my notes.
> Update message in bundle.yaml. Fixes #754

- gistValidationAnnotations.ttl
Fixes #753.
Note that there is no release note for this PR, as the change is too trivial to document.
> Update skos:definition of gist:nonConformingLabel. Fixes #753.

- .github/workflows/validate.yaml
- docs/release_notes/issue650.md
- gistCore.ttl
Fixes #650
Removes
- gist:TimeZone
- gist:TimeZoneStandard
- gist:hasOffsetToUniversal
- gist:usesTimeZoneStandard
> Remove TimeZone & etc. Fixes #650

- docs/release_notes/pr813.md
- gistCore.ttl
Fixes #506.
This PR includes changes related to the removal of inverse properties from gist:
- All inverses removed. (Inverse working group has proposed which directions to keep in gist.)
- Relevant axioms have been tweaked to include only the properties that will remain in gist. A common change was to switch out a property restriction with its inverse property. For example:
```
a owl:Restriction ;
owl:onProperty gist:isBasisFor ;
owl:someValuesFrom gist:Event ;
```
becomes
```
a owl:Restriction ;
owl:onProperty [ owl:inverseOf gist:isBasedOn ] ;
owl:someValuesFrom gist:Event ;
```
- If the direction we are removing contained more information than its inverse, the additional information was maintained in some cases where useful. (See, e.g., `isGovernedBy`.)
**Breakdown** (updated after …
> Remove inverses. Fixes #506.

- docs/release_notes/pr834.md
- tools/serializer/pre-commit
Fixes #832 
I think this change will fix the problem reported by Rebecca that our pre-commit hook was failing on files that had been deleted.
> Fix pre-commit error on deleted files - Fixes #832

- docs/release_notes/pr826.md
- gistCore.ttl
This PR removed dateTime restrictions from `gist:ContingentEvent` and adds a `skos:example`. 
See the issue here: https://github.com/semanticarts/gist/issues/776
> Bugfix/776 contingent event. Fixes #776.

- docs/release_notes/pr811.md
- gistCore.ttl
> Update annotations on gist:isAllocatedBy. Fixes #530.

- docs/release_notes/issue733.md
- gistCore.ttl
Hi Rebecca,
This PR covers all changes for 733:
1) removed gist:hasSubTask and gist:hasDirectSubTask (since this is a major change coming up, removing them entirely per our deletion policy).
2) updated restriction on gist:ProjectExecution to reference gist:hasPart instead of gist:hasSubTask.
3) added release note file with change list.
Please let me know if I've missed anything. Thanks!
-Heather
> issue 733 - gist:hasSubTask and gist:hasDirectSubTask - all changes

- gistCore.ttl
This doesn't need a release note because the error was introduced since the last release.
> Add prefLabel to ScheduledEvent

- gistCore.ttl
This brings in the TimeInterval PR that seems to have been lost.
> Re-commit lost PR: added TimeInterval class

- gistCore.ttl
- gistSubClassAssertions.ttl
Peter found at the last minute that TreatyOrganization was still present in gistCore.ttl. This PR is to remove it consistent with the intention of issue #766 and pr #825
> Remove TreatyOrganization (accidentally left in)

- docs/ReleaseNotes.md
When used in combination with https://github.com/semanticarts/ontology-toolkit/releases/tag/v1.7.4, resolves #923
> Add newline to property format HTML table. Fixes #923

- docs/Namespace.md
- docs/release_notes/patch-919-wrong-apostrophe
Fixes #919
I also fixed this on the version that is hosted for the new gist namespace.
> Fix wrong apostrophe in docs/Namespace.md

- gistCore.ttl
Fixes #775.
Temporary fix to ensure `rdfs:isDefinedBy` assertions are generated for all instances.
> Add missing owl:Thing assertions

- bundle.yaml
- docs/release_notes/issue-922-bundler
- docs/release_notes/patch-919-wrong-apostrophe
Fixes #922.
Two changes:
* gistValidationAnnotations.ttl is not included in download package
* rdfsAnnotations files have versioned filenames prefixed with "gist" - e.g., "gistRdfsAnnotations12.0.1.ttl" instead of "rdfsAnnotations.ttl".
I've tested these on my end. Please run the bundler and test for both of these changes.
> Bundle.yaml updates. Fixes #922

- docs/ReleaseNotes.md
- docs/release_notes/issue-917-readme-updates
- docs/release_notes/issue-922-bundler
- docs/release_notes/patch-919-wrong-apostrophe
- gistSubClassAssertions.ttl
PR to merge v12.0.1 release branch into `master`.
Should follow #936, which merges the release branch into `develop`.
> Release 12.0.1 (into `master`)

- docs/release_notes/820-isCharacterizedAs.md
- gistCore.ttl
Deprecated `isCharacterizedAs`
Updated: https://github.com/semanticarts/gist/issues/947
Fixes #820.
> Issue 820 is characterized as

- docs/release_notes/897-owl-imports.md
- gistPrefixDeclarations.ttl
- gistSubClassAssertions.ttl
- gistValidationAnnotations.ttl
> 897 owl imports

- docs/release_notes/372-text-datatype-properties.md
- gistCore.ttl
Fixes #372 
- Deprecated `tagText`, to be replaced by `containedText`.
- `containedText` 
- Added domainIncludes `Tag` and `Text` 
- Removed reference to Text class in the definition
- Added examples
> Issue 372 text datatype properties

- docs/release_notes/531-extend-symbol-predicates.md
- gistCore.ttl
- gistValidationAnnotations.ttl
Fixes #531 .
- Deprecated predicates: `gist:unitSymbol`, `gist:unitSymbolHtml` and `gist:unitSymbolUnicode`. 
- Added predicates: `gist:symbol`, `gist:symbolHtml` and `gist:symbolUnicode`.
- Added symbol triples for existing units, anticipating the removal of `gist:UnitSymbol`.
- Added `nonConformingLabel` triple for `symbolUnicode` in `gistValidationAnnotations.ttl`
> 531 extend symbol predicates

- docs/release_notes/1007-pre-commit
- tools/pre-commit
- tools/setup.cmd
> Fix serializer pre-commit permissions problem

- docs/release_notes/PR1012-core-filemode-config
- tools/pre-commit
- tools/setup.cmd
@Jamie-SA On Mac files become non-executable when committed. This means that you have to make setup.cmd executable to run it, at which point git records a change and wants to re-commit. Setting the flag in setup.cmd means git will ignore this change. 
See https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode and
https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes
> Ignore executable flag on files

- docs/release_notes/934-skeletal-definitions-for-DL.md
- gistCore.ttl
- validation/shapes/ontologyShapes.ttl
Adding skeletal definitions for SKOS terms. Omitting definitions for SHACL terms in anticipation of #1001.
Closes #934.
> Add skeletal definitions for SKOS terms

- docs/release_notes/issue865-rename-master-to-main.md
Closes #865.
Branch has been renamed - this PR adds a release note.
Steps to update:
- Fetch the remote
- Track branch `main`
- Delete local branch `master`
> Add release note for issue 865 (change branch master to main)

- docs/release_notes/issue-878-TemporalRelation-drop-endDate-restriction.md
- docs/release_notes/issue-925-TimeInterval-duration-restriction.md
- ontologies/gistCore.ttl
A couple major changes (#969 & #970) were merged into develop prior to the 12.1.0 minor release. To keep the release at the minor level, this PR backs out these major changes.
The changes are set to be added back in major release 13.0.0. See #1046.
> Back out major changes from 12.1.0 release

- docs/release_notes/Issue-944-tweaks-to-OrderedMember-and-hasFirstMember.md
- ontologies/gistCore.ttl
Fixes #944
- tweaked `scopeNote` for `hasFirstMember`: updated language to reflect that strict orderings *are* allowed
- added `providesOrderFor` restriction to `OrderedMember`
- change filter class for `hasFirstMember` restriction on `OrderedCollection` from `owl:Thing` to `OrderedMember`
> Bugfix/issue 944: tweaks to ordered member and has first member

- docs/release_notes/1046-TimeInterval-TemporalRelation.md
- ontologies/gistCore.ttl
Closes #1046.
This PR reimplements changes originally made in #969 and #970 for v12.1.0. Since they were major changes and v12.1.0 was a minor release, these changes had to be backed out (in #1047).
Note: In #969, I originally listed the removal of the `endDateTime` restriction on `TemporalRelation` as a minor change since the effect on inference was relatively small. I believe that during the v12.1.0 release process we reconsidered and bumped it up to a major change, which is why the change needed to be backed out along with #970.
Original issues:
- #878 
- #925
> Finalize restrictions on `gist:TimeInterval` and `gist:TemporalRelation`

- docs/gistStyleGuide.md
- docs/release_notes/issue812-geo-predicates
- ontologies/gistCore.ttl
Fixes #809 - see https://github.com/semanticarts/gist/issues/947#issuecomment-1679565100
Fixes #812 
NB: I've deliberately kept the full prefLabel "is geographically contained in" for `isGeoContainedIn`. This is a bending of our rule about constructing pref labels, but in this case is warranted, in my opinion. I've updated the style guide to reflect this change.
> Remove occupies predicates and shorten isGeographicallyContainedIn 

- docs/ReleaseNotes.md
- docs/release_notes/Issue-899-isGovernedBy.md
- ontologies/gistCore.ttl
Fixes #899
Removed domain and range from gist:isGovernedBy
> Removed domain and range from gist:isGovernedBy

- bundle.yaml
- docs/release_notes/pr1097-build-updates
Closes #1041.
Closes #1058.
Closes #1082.
This PR contains the following changes:
* Change name of generated RDFS annotations file from `rdfsAnnotations` to `gistRdfsAnnotations`.
* Adds latest version of EDM serializer (v. 2).
* Combines two bundle actions together.
> Build updates

- docs/release_notes/issue1115-deprecate-hasSuperCategory
- ontologies/gistCore.ttl
hasSuperCategory is deprecated (redundant with gist:hasBroader)
rename hasDirectSuperCategory to hasDirectBroader, a sub property of hasBroader
rename hasUniqueSuperCategory to hasUniqueBroader, a sub property of hasBroader
change class expressions as needed
closes issue #1115
> deprecate hasSuperCategory and rename its sub properties

- .gitignore
- bundle.yaml
- migration/v13.0/README.md
* Make sure preformatted blocks properly render in HTML
* Properly patch local and relative documentation links in the README
> Fix minor nits in migration README

- docs/release_notes/issue1139-altitude-pref-label.md
- ontologies/gistCore.ttl
closes #1139 
copy-paste error resulted in altitude having prefLabel "area"
changed prefLabel to "altitude"
> change prefLabel of altitude from area to altitude

- docs/release_notes/issue1134-geosegment-definition.md
- ontologies/gistCore.ttl
> fix definition of Geo segment

- docs/release_notes/issue1165-remove-geosegment.md
- ontologies/gistCore.ttl
Remove GeoSegment, change GeoRoute class equivalence to say it is an ordered collection whose members are GeoPoints (old class equivalence incorrectly said it was an ordered collection with GeoSegments as parts).
Closes #1165
> fix geo route and remove geo segment

- docs/release_notes/issue1191-add-Assignment-class.md
- ontologies/gistCore.ttl
> Add `gist:Assignment` class and corresponding predicates

- docs/release_notes/issue1214-improve-pre-commit-hook
- tools/serializer/pre-commit
Fixes #1214
I changed the pre-commit to:
- Prefer RDF_TOOLKIT_JAVA_HOME over JAVA_HOME, since it is the more specific name.
- If neither of those work, use a java executable if one is available in the PATH.
- Removed some trailing spaces.
> Support java executable in path

- docs/release_notes/issue1172-organization-definition.md
- ontologies/gistCore.ttl
> Update definition and scope note of gist:Organization
