semanticarts/gist

OntologyFiles/gistTop.owl

Minor fix 2020 02 04

---

doc/ReleaseNotes.md

Started w/ a clean `develop` and re-applied your changes. If this looks right to you, please approve and close the other PR.

Move release notes and minor markdown fix (Rebecca)

---

OntologyFiles/gistAddress.owl
OntologyFiles/gistAgreement.owl
OntologyFiles/gistCategory.owl
OntologyFiles/gistContent.owl
OntologyFiles/gistCore.owl
OntologyFiles/gistEvent.owl
OntologyFiles/gistIntention.owl
OntologyFiles/gistIoT.owl
OntologyFiles/gistNetwork.owl
OntologyFiles/gistTemporalRelation.owl
OntologyFiles/gistTime.owl
OntologyFiles/gistTop.owl
OntologyFiles/gistUnitDim.owl

Used ispell to automate correction

Correct typos and misspellings in all annotations. Fixes #210.

---

doc/gistStyleGuide.md

Sorry, I forgot to create an issue for this. It just addresses the question I had at the meeting about whether we are committing to OWL DL, for the purposes of adding to the style guide.

Confirm the use of OWL DL rather than Full

---

OntologyFiles/gistTop.owl
OntologyFiles/gistUnit.owl

- Added cardinality restrictions to AreaUnit and VolumeUnit
- Made unit classes disjoint

Unit cardinality restrictions closes #69

---

OntologyFiles/gistTop.owl

@uscholdm I have not added to the release notes for this item. It seems to me we don't want to put such a trivial item in the release notes -

Improve the definition of SimpleUnitOfMeasure (stylistic change only). Fixes #84.

---

tools/release-gist.bash

Putting this into source control.
Closes #249

Adding release-gist.bash script

---

docs/ReleaseNotes.md

fixes issue #256  - correcting the issue number in the release notes from 90 to 80

issue #256

---

bundle.yaml

Broke it into 3 steps, as we discussed. There is no issue that asks for this, should we have something in the release notes?

Add definedBy action to bundle

---

docs/ReleaseNotes.md

9.3.0 Release notes

---

docs/ReleaseNotes.md

Fixes #325.
@daliadahleh This should be included in the 9.3.0 release.

De-lint 9.3.0 release notes

---

docs/Contributing.md
docs/ReleaseNotes.md
docs/ReleaseNotesTemplate.md

Add release notes template

---

docs/ReleaseNotes.md
gistCore.ttl
gistDeprecated.ttl

Deprecate gist:_unitedNations

---

docs/ReleaseNotes.md

Restored text lost between merges. Assumes PR #356 will be included in release.

Minor fixes to release notes - no substantive changes

---

docs/ReleaseNotes.md
gistCore.ttl

Fixes #110.
@marksem Added a release note to encompass both this issue and #343 for Place.

Removed union class equivalence assertion from gist:Artifact

---

docs/ReleaseNotes.md
gistCore.ttl

Fixes #64, #334. Also a couple of tweaks to release notes.

Trivial bug fixes to axioms in some geo terms

---

tools/release-gist.bash

Updates the release script after new file types were added.

Update handles new files

---

docs/ReleaseNotes.md
gistCore.ttl

I've added a release note but the release note format will change based on issue #401, so I have not formatted it in any particular way with this PR.

Fix label of TaskTemplate. Fixes #407

---

docs/Contributing.md

Document new policy on PR submission by external contributors.

Document new policy on PR submission by external contributors. Fixes #403.

---

docs/ReleaseNotes.md
gistCore.ttl

NOTE:  To avoid merge conflicts, I merged the branch for PR: https://github.com/semanticarts/gist/pull/479 into the branch for this PR. So, before merging this PR it may be best to merge PR: https://github.com/semanticarts/gist/pull/479. 
If there is a better way to do this, I'm all ears.

Basis for issue139. Fixes #139.

---

.github/workflows/validate.yaml
ontologyShapes.ttl

Run bundle validation on push.

Initial CI support 

---

docs/gistStyleGuide.md

Primarily reformatting for readability; added TOC.

gist style guide updates

---

docs/ReleaseNotes.md
gistCore.ttl

Update annotations including examples for the coherent unit classes.

Issue 146 coherent units

---

gistCore.ttl

"A function or piece of work to be done or undertaken, usually within a certain time."

Proposed skos:definition of Task

---

docs/ReleaseNotes.md
gistCore.ttl

Added scopeNote to use SHACL if needed.
Also updated release notes.

Removing min cardinality of zero restriction on ProductUnit. Fixes #582.

---

docs/Contributing.md

Add notes about pre-commit hook and a few other minor topics.

Update Contributing.md. Fixes #580.

---

migration/v11.0/input/detect.ttl

Added test data to verify that the recently added query are working.
This PR is stacked on the release PR so it can be merged directly into it if desired.

Add test data to verify detect_range_changed

---

gistCore.ttl

Fix gist:actualStartDateTime skos:definition

---

docs/ReleaseNotes.md
gistCore.ttl

Replace rdfs:range on gist:conformsTo with gist:rangeIncludes

---

README.md

Fixes #727
Some additions to the README file to point users to educational resources.

Fixes #727 - Add pointers to educational material to README

---

bundle.yaml
docs/ReleaseNotes.md
gistCore.ttl
gistDeprecated.ttl
gistMediaTypes.ttl
gistPrefixDeclarations.ttl
gistValidationAnnotations.ttl
ontologyShapes.ttl

In modifying bundle.yaml I noticed a few small errors in imports and preflabels in the non-core ontology files, and have fixed those as well though not directly related to this issue.

Add prefix declarations. Fixes #684.

---

gistCore.ttl

Adding the TimeInterval class back to gistCore

added TimeInterval class

---

docs/release_notes/issue650.md
docs/release_notes/pr788.md
docs/release_notes/pr793.md
docs/release_notes/pr822.md
docs/release_notes/pr825.md
docs/release_notes/pr828.md

Release note fixes. Fixes #829.

---

tools/pre-commit
tools/serializer/pre-commit
tools/setup.cmd

Modify setup script to make pre-commit hooks executable (needed on Mac). Fixes #823

---

docs/ReleaseNotes.md
docs/release_notes/PR777.md
gistCore.ttl

Rework Event and Task classes. Fixes #760.

---

docs/Contributing.md
docs/release_notes/issue817.md
docs/release_notes/pr847.md
gistCore.ttl

Fixes #846. 
Due to some technical issues regarding branch names, I had to recreate the former PR #847. You can refer to comments there.

Add MonetaryPerDuration and CurrencyPerDurationUnit classes. Fixes #846

---

gistCore.ttl

I'm not sure what happened, but somehow or other the serializer didn't get run on my last PR.

Run serializer 

---

docs/Namespace.md

Update Namespace.md to replace quote characters

---

gistCore.ttl

One scopeNote change from this PR was lost. This is an attempt to fix that with git magic.

Re-apply previous commit: Remove TimeZone & etc

---

docs/Namespace.md

Update namespace & IRIs

---

gistCore.ttl
tools/serializer/pre-commit

Fix pre-commit hook

---

docs/Namespace.md

Update Namespace.md document for new namespace & IRIs

---

tools/subclass_inferences/materialize_subclass_inferences.py

Update gist namespace in subclass generator. Fixes #893.

---

docs/release_notes/issue-878-TemporalRelation-drop-endDate-restriction.md
gistCore.ttl

Drop end date restriction on `TemporalRelation`

---

docs/release_notes/issue-925-TimeInterval-duration-restriction.md
gistCore.ttl

Add restrictions to `TimeInterval`

---

docs/release_notes/950-TimeInterval-and-Event.md
gistCore.ttl

950 time interval and event

---

docs/release_notes/issue-961-percent-typo.md
gistCore.ttl

Fix typo in scope note for `_percent`

---

README.md

Add gist link to README

---

docs/release_notes/431-Specification-definition.md
gistCore.ttl

Fixes #431
Updated definition of Specification

Updated definition of Specification

---

docs/release_notes/521-definition-of-transaction.md
gistCore.ttl

Updated annotations for gist:Transaction

---

docs/release_notes/439-hasMember-definition.md
gistCore.ttl

Updated definition of hasMember

Updated definition of hasMember

---

docs/release_notes/1004-uniqueText-scopeNote.md
gistCore.ttl

Add scopeNote to uniqueText explaining that uniqueness only goes in one direction.

Add scopeNote to uniqueText

---

docs/release_notes/965-magnitude-definition.md
gistCore.ttl

Fixes #965 
It was likely a copy/paste error.

Fixed definition of Magnitude.

---

docs/release_notes/issue-396-message-definition.md
gistCore.ttl

Corrected definition of gist:Message

Issue 396 message definition

---

docs/release_notes/issue806-living-thing
gistCore.ttl

Changed restriction on gist:LivingThing

---

docs/release_notes/607-isRecognizedBy.md
gistCore.ttl

- Updated annotations for `gist:isRecognizedBy`
- Deprecated `gist:isRecognizedDirectlyBy`

Issue 607 is recognized by

---

ontologies/gistSubClassAssertions.ttl
tools/subclass_inferences/materialize_subclass_inferences.py

Fixed paths in python script and updated the output file.

Materialize subclass inferences updates

---

docs/release_notes/releaseNote1063.md
ontologies/gistCore.ttl

Removed Domain and Range from `gist:allows`

---

docs/ChangeAndReleaseManagement.md
docs/Contributing.md
docs/release_notes/pr1098-style-guide

Update definition of patch release

---

docs/gistStyleGuide.md
docs/release_notes/issue973-patch-versions

Closes #511 - Best practices for negative examples in `skos:example`
Closes #966 - Using or not using ontology terms in annotations
Closes #1080 - Fixed broken link to OntoClean
Closes #1086 - Best practices for inverses (don't)

Style guide updates

---

LICENSE.txt
README.md
docs/release_notes/issue244_upgrade_license
ontologies/gistCore.ttl
ontologies/gistMediaTypes.ttl
ontologies/gistPrefixDeclarations.ttl
ontologies/gistValidationAnnotations.ttl

Closes #244.
@Jamie-SA After the release, can you update the license reference on the website to this?
```
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. In addition,  we require that any gist concepts remain in the gist namespace (https://w3id.org/semanticarts/ns/ontology/gist/), and that you not define your own terms within the gist namespace.
```

Upgrade license

---

ontologies/gistCore.ttl

Use same wording as on other datetime predicates

Update annotations on endDateTime and startDateTime 

---

.github/workflows/validate.yaml

Update github workflow to use newer Action versions

---

docs/release_notes/issue1151-skos-annotation-stubs.md
ontologies/gistCore.ttl

Issue #1151 Add missing SKOS stubs

---

docs/release_notes/issue1093-description-range.md
ontologies/gistCore.ttl

Add range to gist:description

---

docs/release_notes/issue977-license-datatype
ontologies/gistCore.ttl
ontologies/gistMediaTypes.ttl
ontologies/gistPrefixDeclarations.ttl
ontologies/gistValidationAnnotations.ttl

Change type of gist:license values to xsd:anyURI

---

.markdownlint.json
bundle.yaml
docs/release_notes/issue383-versioned-defined-by.md

Use versioned IRIs in rdfs:isDefinedBy

---

tools/subclass_inferences/materialize_subclass_inferences.py

Update license in ontology header in materialize subclasses script

---

docs/release_notes/issue1229-typo-TemporalRelation.md
ontologies/gistCore.ttl

Fix TemporalRelation scopeNote typo

---

docs/release_notes/issue1163-produces-to-isProducedBy
docs/release_notes/issue1163-produces-to-isProducedBy.md
ontologies/gistCore.ttl

Replaced produces with isProducedBy
